-- MySQL Script generated by MySQL Workbench
-- Thu Mar 30 13:59:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Blok`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Blok` (
  `idBlok` INT NOT NULL,
  PRIMARY KEY (`idBlok`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `idStudent` INT NOT NULL,
  `krestniJmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `trida(obor)` VARCHAR(45) NOT NULL,
  `Blok_idBlok` INT NOT NULL,
  PRIMARY KEY (`idStudent`, `Blok_idBlok`),
  INDEX `fk_Student_Blok_idx` (`Blok_idBlok` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Blok`
    FOREIGN KEY (`Blok_idBlok`)
    REFERENCES `mydb`.`Blok` (`idBlok`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Firma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Firma` (
  `idFirma` INT NOT NULL,
  `nazev` VARCHAR(45) NOT NULL,
  `potřeby` VARCHAR(45) NOT NULL,
  `obory` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFirma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ucebna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ucebna` (
  `idUcebna` INT NOT NULL,
  `cisloUcebny` VARCHAR(45) NOT NULL,
  `Firma_idFirma` INT NOT NULL,
  `kapacity` INT NOT NULL,
  `vybavení` VARCHAR(45) NULL,
  PRIMARY KEY (`idUcebna`, `Firma_idFirma`),
  INDEX `fk_Ucebna_Firma1_idx` (`Firma_idFirma` ASC) VISIBLE,
  CONSTRAINT `fk_Ucebna_Firma1`
    FOREIGN KEY (`Firma_idFirma`)
    REFERENCES `mydb`.`Firma` (`idFirma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Firma_has_Blok`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Firma_has_Blok` (
  `Firma_idFirma` INT NOT NULL,
  `Blok_idBlok` INT NOT NULL,
  PRIMARY KEY (`Firma_idFirma`, `Blok_idBlok`),
  INDEX `fk_Firma_has_Blok_Blok1_idx` (`Blok_idBlok` ASC) VISIBLE,
  INDEX `fk_Firma_has_Blok_Firma1_idx` (`Firma_idFirma` ASC) VISIBLE,
  CONSTRAINT `fk_Firma_has_Blok_Firma1`
    FOREIGN KEY (`Firma_idFirma`)
    REFERENCES `mydb`.`Firma` (`idFirma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Firma_has_Blok_Blok1`
    FOREIGN KEY (`Blok_idBlok`)
    REFERENCES `mydb`.`Blok` (`idBlok`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
