-- MySQL Script generated by MySQL Workbench
-- Wed Apr 26 10:24:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- nahradte <cislodb> se jmenem databaze

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema <cislodb>
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema <cislodb>
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `<cislodb>` DEFAULT CHARACTER SET utf8 ;
USE `<cislodb>` ;

-- -----------------------------------------------------
-- Table `<cislodb>`.`Blok`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `<cislodb>`.`Blok` (
  `idBlok` INT NOT NULL,
  PRIMARY KEY (`idBlok`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `<cislodb>`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `<cislodb>`.`Student` (
  `idStudent` INT NOT NULL AUTO_INCREMENT,
  `krestniJmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `trida(obor)` VARCHAR(45) NOT NULL,
  `Blok_idBlok` INT NOT NULL,
  `heslo` VARCHAR(45) NULL,
  PRIMARY KEY (`idStudent`, `Blok_idBlok`),
  INDEX `fk_Student_Blok_idx` (`Blok_idBlok` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Blok`
    FOREIGN KEY (`Blok_idBlok`)
    REFERENCES `<cislodb>`.`Blok` (`idBlok`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `<cislodb>`.`Ucebna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `<cislodb>`.`Ucebna` (
  `idUcebna` INT NOT NULL AUTO_INCREMENT,
  `cisloUcebny` VARCHAR(45) NOT NULL,
  `kapacity` INT NOT NULL,
  PRIMARY KEY (`idUcebna`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `<cislodb>`.`Firma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `<cislodb>`.`Firma` (
  `idFirma` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  `Ucebna_idUcebna` INT NOT NULL,
  `o firmě` VARCHAR(1000) NULL,
  `název prezentace` VARCHAR(1000) NULL,
  PRIMARY KEY (`idFirma`, `Ucebna_idUcebna`),
  INDEX `fk_Firma_Ucebna1_idx` (`Ucebna_idUcebna` ASC) VISIBLE,
  CONSTRAINT `fk_Firma_Ucebna1`
    FOREIGN KEY (`Ucebna_idUcebna`)
    REFERENCES `<cislodb>`.`Ucebna` (`idUcebna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `<cislodb>`.`Firma_has_Blok`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `<cislodb>`.`Firma_has_Blok` (
  `Firma_idFirma` INT NOT NULL,
  `Blok_idBlok` INT NOT NULL,
  `hodina` INT NULL,
  PRIMARY KEY (`Firma_idFirma`, `Blok_idBlok`),
  INDEX `fk_Firma_has_Blok_Blok1_idx` (`Blok_idBlok` ASC) VISIBLE,
  INDEX `fk_Firma_has_Blok_Firma1_idx` (`Firma_idFirma` ASC) VISIBLE,
  CONSTRAINT `fk_Firma_has_Blok_Firma1`
    FOREIGN KEY (`Firma_idFirma`)
    REFERENCES `<cislodb>`.`Firma` (`idFirma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Firma_has_Blok_Blok1`
    FOREIGN KEY (`Blok_idBlok`)
    REFERENCES `<cislodb>`.`Blok` (`idBlok`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `<cislodb>`.`su`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `<cislodb>`.`su` (
  `idsu` INT NOT NULL,
  `login` VARCHAR(45) NULL,
  `heslo` VARCHAR(45) NULL,
  PRIMARY KEY (`idsu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `<cislodb>`.`potřeby`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `<cislodb>`.`potřeby` (
  `idpotřeby` INT NOT NULL,
  `jméno` VARCHAR(45) NULL,
  PRIMARY KEY (`idpotřeby`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `<cislodb>`.`Firma_has_potřeby`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `<cislodb>`.`Firma_has_potřeby` (
  `Firma_idFirma` INT NOT NULL,
  `Firma_Ucebna_idUcebna` INT NOT NULL,
  `potřeby_idpotřeby` INT NOT NULL,
  PRIMARY KEY (`Firma_idFirma`, `Firma_Ucebna_idUcebna`, `potřeby_idpotřeby`),
  INDEX `fk_Firma_has_potřeby_potřeby1_idx` (`potřeby_idpotřeby` ASC) VISIBLE,
  INDEX `fk_Firma_has_potřeby_Firma1_idx` (`Firma_idFirma` ASC, `Firma_Ucebna_idUcebna` ASC) VISIBLE,
  CONSTRAINT `fk_Firma_has_potřeby_Firma1`
    FOREIGN KEY (`Firma_idFirma` , `Firma_Ucebna_idUcebna`)
    REFERENCES `<cislodb>`.`Firma` (`idFirma` , `Ucebna_idUcebna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Firma_has_potřeby_potřeby1`
    FOREIGN KEY (`potřeby_idpotřeby`)
    REFERENCES `<cislodb>`.`potřeby` (`idpotřeby`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `<cislodb>`.`vybavení`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `<cislodb>`.`vybavení` (
  `Ucebna_idUcebna` INT NOT NULL,
  `potřeby_idpotřeby` INT NOT NULL,
  PRIMARY KEY (`Ucebna_idUcebna`, `potřeby_idpotřeby`),
  INDEX `fk_Ucebna_has_potřeby_potřeby1_idx` (`potřeby_idpotřeby` ASC) VISIBLE,
  INDEX `fk_Ucebna_has_potřeby_Ucebna1_idx` (`Ucebna_idUcebna` ASC) VISIBLE,
  CONSTRAINT `fk_Ucebna_has_potřeby_Ucebna1`
    FOREIGN KEY (`Ucebna_idUcebna`)
    REFERENCES `<cislodb>`.`Ucebna` (`idUcebna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ucebna_has_potřeby_potřeby1`
    FOREIGN KEY (`potřeby_idpotřeby`)
    REFERENCES `<cislodb>`.`potřeby` (`idpotřeby`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `<cislodb>`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `<cislodb>`.`table1` (
  `idobory` INT NOT NULL,
  `zkratka` VARCHAR(5) NULL,
  `plný_název` VARCHAR(45) NULL,
  PRIMARY KEY (`idobory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `<cislodb>`.`Firma_has_table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `<cislodb>`.`Firma_has_table1` (
  `Firma_idFirma` INT NOT NULL,
  `Firma_Ucebna_idUcebna` INT NOT NULL,
  `table1_idobory` INT NOT NULL,
  PRIMARY KEY (`Firma_idFirma`, `Firma_Ucebna_idUcebna`, `table1_idobory`),
  INDEX `fk_Firma_has_table1_table11_idx` (`table1_idobory` ASC) VISIBLE,
  INDEX `fk_Firma_has_table1_Firma1_idx` (`Firma_idFirma` ASC, `Firma_Ucebna_idUcebna` ASC) VISIBLE,
  CONSTRAINT `fk_Firma_has_table1_Firma1`
    FOREIGN KEY (`Firma_idFirma` , `Firma_Ucebna_idUcebna`)
    REFERENCES `<cislodb>`.`Firma` (`idFirma` , `Ucebna_idUcebna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Firma_has_table1_table11`
    FOREIGN KEY (`table1_idobory`)
    REFERENCES `<cislodb>`.`table1` (`idobory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
