-- MySQL Script generated by MySQL Workbench
-- Fri May 12 19:25:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`blok`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`blok` ;

CREATE TABLE IF NOT EXISTS `mydb`.`blok` (
  `idBlok` INT NOT NULL,
  PRIMARY KEY (`idBlok`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `idStudent` INT NOT NULL AUTO_INCREMENT,
  `krestniJmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `trida(obor)` VARCHAR(45) NOT NULL,
  `Blok_idBlok` INT NOT NULL,
  `heslo` VARCHAR(45) NULL,
  PRIMARY KEY (`idStudent`, `Blok_idBlok`),
  INDEX `fk_Student_Blok_idx` (`Blok_idBlok` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Blok`
    FOREIGN KEY (`Blok_idBlok`)
    REFERENCES `mydb`.`blok` (`idBlok`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ucebna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ucebna` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ucebna` (
  `idUcebna` INT NOT NULL AUTO_INCREMENT,
  `cisloUcebny` VARCHAR(45) NOT NULL,
  `kapacity` INT NOT NULL,
  PRIMARY KEY (`idUcebna`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`firma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`firma` ;

CREATE TABLE IF NOT EXISTS `mydb`.`firma` (
  `idFirma` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  `Ucebna_idUcebna` INT NULL,
  `oFirme` VARCHAR(1000) NULL,
  `nazevPrezentace` VARCHAR(1000) NULL,
  PRIMARY KEY (`idFirma`),
  INDEX `fk_Firma_Ucebna1_idx` (`Ucebna_idUcebna` ASC) VISIBLE,
  CONSTRAINT `fk_Firma_Ucebna1`
    FOREIGN KEY (`Ucebna_idUcebna`)
    REFERENCES `mydb`.`ucebna` (`idUcebna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`firmaHasBlok`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`firmaHasBlok` ;

CREATE TABLE IF NOT EXISTS `mydb`.`firmaHasBlok` (
  `Firma_idFirma` INT NOT NULL,
  `Blok_idBlok` INT NOT NULL,
  `hodina` INT NULL,
  PRIMARY KEY (`Firma_idFirma`, `Blok_idBlok`),
  INDEX `fk_Firma_has_Blok_Blok1_idx` (`Blok_idBlok` ASC) VISIBLE,
  INDEX `fk_Firma_has_Blok_Firma1_idx` (`Firma_idFirma` ASC) VISIBLE,
  CONSTRAINT `fk_Firma_has_Blok_Firma1`
    FOREIGN KEY (`Firma_idFirma`)
    REFERENCES `mydb`.`firma` (`idFirma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Firma_has_Blok_Blok1`
    FOREIGN KEY (`Blok_idBlok`)
    REFERENCES `mydb`.`blok` (`idBlok`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`su`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`su` ;

CREATE TABLE IF NOT EXISTS `mydb`.`su` (
  `idsu` INT NOT NULL,
  `login` VARCHAR(45) NULL,
  `heslo` VARCHAR(45) NULL,
  PRIMARY KEY (`idsu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zarizeni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`zarizeni` ;

CREATE TABLE IF NOT EXISTS `mydb`.`zarizeni` (
  `idpotreby` INT NOT NULL,
  `jméno` VARCHAR(45) NULL,
  PRIMARY KEY (`idpotreby`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`firmaHasPotreby`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`firmaHasPotreby` ;

CREATE TABLE IF NOT EXISTS `mydb`.`firmaHasPotreby` (
  `firma_idfirma` INT NOT NULL,
  `potreby_idpotreby` INT NOT NULL,
  PRIMARY KEY (`firma_idfirma`, `potreby_idpotreby`),
  INDEX `fk_Firma_has_potřeby_potřeby1_idx` (`potreby_idpotreby` ASC) VISIBLE,
  INDEX `fk_Firma_has_potřeby_Firma1_idx` (`firma_idfirma` ASC) VISIBLE,
  CONSTRAINT `fk_Firma_has_potřeby_Firma1`
    FOREIGN KEY (`firma_idfirma`)
    REFERENCES `mydb`.`firma` (`idFirma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Firma_has_potřeby_potřeby1`
    FOREIGN KEY (`potreby_idpotreby`)
    REFERENCES `mydb`.`zarizeni` (`idpotreby`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ucebnaHasVybaveni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ucebnaHasVybaveni` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ucebnaHasVybaveni` (
  `Ucebna_idUcebna` INT NOT NULL,
  `potreby_idpotreby` INT NOT NULL,
  PRIMARY KEY (`Ucebna_idUcebna`, `potreby_idpotreby`),
  INDEX `fk_Ucebna_has_potřeby_potřeby1_idx` (`potreby_idpotreby` ASC) VISIBLE,
  INDEX `fk_Ucebna_has_potřeby_Ucebna1_idx` (`Ucebna_idUcebna` ASC) VISIBLE,
  CONSTRAINT `fk_Ucebna_has_potřeby_Ucebna1`
    FOREIGN KEY (`Ucebna_idUcebna`)
    REFERENCES `mydb`.`ucebna` (`idUcebna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ucebna_has_potřeby_potřeby1`
    FOREIGN KEY (`potreby_idpotreby`)
    REFERENCES `mydb`.`zarizeni` (`idpotreby`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`obory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`obory` ;

CREATE TABLE IF NOT EXISTS `mydb`.`obory` (
  `idobory` INT NOT NULL,
  `zkratka` VARCHAR(5) NULL,
  `plnyNazev` VARCHAR(45) NULL,
  PRIMARY KEY (`idobory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`firmaHasObory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`firmaHasObory` ;

CREATE TABLE IF NOT EXISTS `mydb`.`firmaHasObory` (
  `Firma_idFirma` INT NOT NULL,
  `obory_idobory` INT NOT NULL,
  PRIMARY KEY (`Firma_idFirma`, `obory_idobory`),
  INDEX `fk_Firma_has_obory_obory1_idx` (`obory_idobory` ASC) VISIBLE,
  INDEX `fk_Firma_has_obory_Firma1_idx` (`Firma_idFirma` ASC) VISIBLE,
  CONSTRAINT `fk_Firma_has_obory_Firma1`
    FOREIGN KEY (`Firma_idFirma`)
    REFERENCES `mydb`.`firma` (`idFirma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Firma_has_obory_obory1`
    FOREIGN KEY (`obory_idobory`)
    REFERENCES `mydb`.`obory` (`idobory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`zarizeni`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`zarizeni` (`idpotreby`, `jméno`) VALUES (1, 'Robotická ruka');
INSERT INTO `mydb`.`zarizeni` (`idpotreby`, `jméno`) VALUES (2, 'Projektor');
INSERT INTO `mydb`.`zarizeni` (`idpotreby`, `jméno`) VALUES (3, 'Ozvučení');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`obory`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`obory` (`idobory`, `zkratka`, `plnyNazev`) VALUES (1, 'V', 'Informační technologie');
INSERT INTO `mydb`.`obory` (`idobory`, `zkratka`, `plnyNazev`) VALUES (2, 'S', 'Sociálněsprávní činnost');

COMMIT;

